=== Hemazinc123/mfcs-int-1024p/src/main/resources/api/schemas/ItemSupCtyDesc.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.oracle.com/retail/integration/base/bo/ItemSupCtyDesc/v1" xmlns:CustFlexAttriVo="http://www.oracle.com/retail/integration/base/bo/CustFlexAttriVo/v1" xmlns:retailDoc="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://www.oracle.com/retail/integration/base/bo/ItemSupCtyDesc/v1" version="1.0">
   <retailDoc:annotation>
      <retailDoc:documentation>This is root element of this document which contains name space definitions for the document elements.</retailDoc:documentation>
   </retailDoc:annotation>
   <xs:import namespace="http://www.oracle.com/retail/integration/base/bo/CustFlexAttriVo/v1" schemaLocation="CustFlexAttriVo.xsd">
      <retailDoc:annotation>
         <retailDoc:documentation>It's a referenced element. For detailed description, please refer referenced element doc.</retailDoc:documentation>
      </retailDoc:annotation>
   </xs:import>
   <xs:element name="ItemSupCtyDesc">
      <retailDoc:annotation>
         <retailDoc:documentation>Description is not available.</retailDoc:documentation>
      </retailDoc:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element name="item" type="varchar225">
               <retailDoc:annotation>
                  <retailDoc:documentation>Unique identifier for the item.</retailDoc:documentation>
               </retailDoc:annotation>
            </xs:element>
            <xs:element name="supplier" type="varchar210">
               <retailDoc:annotation>
                  <retailDoc:documentation>Unique identifier for the supplier.</retailDoc:documentation>
               </retailDoc:annotation>
            </xs:element>
            <xs:element name="origin_country_id" type="varchar23">
               <retailDoc:annotation>
                  <retailDoc:documentation>The country where the item was manufactured or significantly altered.</retailDoc:documentation>
               </retailDoc:annotation>
            </xs:element>
            <xs:element name="primary_supp_ind" type="varchar23">
               <retailDoc:annotation>
                  <retailDoc:documentation>This field indicates whether this supplier is the primary supplier for the item. Each item can have one and only one primary supplier.</retailDoc:documentation>
               </retailDoc:annotation>
            </xs:element>
            <xs:element name="primary_country_ind" type="varchar21">
               <retailDoc:annotation>
                  <retailDoc:documentation>This field indicates whether this country is the primary country for the item/supplier. Each item/supplier combination can have one and only one primary country.</retailDoc:documentation>
               </retailDoc:annotation>
            </xs:element>
            <xs:element name="unit_cost" type="number20_4">
               <retailDoc:annotation>
                  <retailDoc:documentation>This field contains the current corporate unit cost for the item from the supplier /origin country. This field is stored in the Supplier's currency.</retailDoc:documentation>
               </retailDoc:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="lead_time" type="number4">
               <retailDoc:annotation>
                  <retailDoc:documentation>This field contains the number of days that will elapse between the date an order is written and the delivery to the store or warehouse from the supplier.</retailDoc:documentation>
               </retailDoc:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="pickup_lead_time" type="number4">
               <retailDoc:annotation>
                  <retailDoc:documentation>Contains the time that will be taken to get the item from the supplier to the initial receiving location.</retailDoc:documentation>
               </retailDoc:annotation>
            </xs:element>
            <xs:element name="supp_pack_size" type="number12_4">
               <retailDoc:annotation>
                  <retailDoc:documentation>This field contains the quantity that orders must be placed in multiples of for the supplier for the item.</retailDoc:documentation>
               </retailDoc:annotation>
            </xs:element>
            <xs:element name="inner_pack_size" type="number12_4">
               <retailDoc:annotation>
                  <retailDoc:documentation>This field contains the break pack size for this item from the supplier.</retailDoc:documentation>
               </retailDoc:annotation>
            </xs:element>
            <xs:element name="round_lvl" type="varchar26">
               <retailDoc:annotation>
                  <retailDoc:documentation>This column is used to determine how order quantities will be rounded to case, layer and pallet.</retailDoc:documentation>
               </retailDoc:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="min_order_qty" type="number12_4">
               <retailDoc:annotation>
                  <retailDoc:documentation>This field contains the minimum quantity that can be ordered at one from the supplier for the item.</retailDoc:documentation>
               </retailDoc:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="max_order_qty" type="number12_4">
               <retailDoc:annotation>
                  <retailDoc:documentation>This field contains the maximum quantity that can be ordered at one from the supplier for the item.</retailDoc:documentation>
               </retailDoc:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="packing_method" type="varchar26">
               <retailDoc:annotation>
                  <retailDoc:documentation>This field indicates whether the packing method for the item in the container is flat or hanging.</retailDoc:documentation>
               </retailDoc:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="default_uop" type="varchar26">
               <retailDoc:annotation>
                  <retailDoc:documentation>Contains the default unit of purchase for the item/supplier/country. Valid values include 'C'ase and 'P'allet.</retailDoc:documentation>
               </retailDoc:annotation>
            </xs:element>
            <xs:element name="ti" type="number12_4">
               <retailDoc:annotation>
                  <retailDoc:documentation>Number of shipping units (cases) that make up one tier of the pallet. Multiply TI x HI to get total number of units (cases) in a Pallet.</retailDoc:documentation>
               </retailDoc:annotation>
            </xs:element>
            <xs:element name="hi" type="number12_4">
               <retailDoc:annotation>
                  <retailDoc:documentation>Number of tiers that make up a complete pallet. Multiply TI x HI to get total number of units (cases) in a Pallet.</retailDoc:documentation>
               </retailDoc:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="cost_uom" type="varchar24">
               <retailDoc:annotation>
                  <retailDoc:documentation>A cost UOM is held to allow costs to be managed in a separate UOM to the standard UOM.</retailDoc:documentation>
               </retailDoc:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="tolerance_type" type="varchar26">
               <retailDoc:annotation>
                  <retailDoc:documentation>The unit of tolerance for catch weight simple packs. Valid values are: 'A'-actual 'P' - percent.</retailDoc:documentation>
               </retailDoc:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="max_tolerance" type="number12_4">
               <retailDoc:annotation>
                  <retailDoc:documentation>The maximum tolerance value for the catch weight simple pack.</retailDoc:documentation>
               </retailDoc:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="min_tolerance" type="number12_4">
               <retailDoc:annotation>
                  <retailDoc:documentation>The minimum tolerance value for a catch weight simple pack.</retailDoc:documentation>
               </retailDoc:annotation>
            </xs:element>
            <xs:element maxOccurs="unbounded" minOccurs="0" ref="CustFlexAttriVo:CustFlexAttriVo">
               <retailDoc:annotation>
                  <retailDoc:documentation>References a collection of customer flexible attributes.</retailDoc:documentation>
               </retailDoc:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="round_to_inner_pct" type="number12_4">
               <retailDoc:annotation>
                  <retailDoc:documentation>This column will hold the Inner Rounding Threshold value. During rounding, this value is used to determine whether to round partial Inner quantities up or down. If the Inner-fraction in question is less than the Threshold proportion, it is rounded down; if not, it is rounded up.</retailDoc:documentation>
               </retailDoc:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="round_to_case_pct" type="number12_4">
               <retailDoc:annotation>
                  <retailDoc:documentation>This column will hold the Case Rounding Threshold value. During rounding, this value is used to determine whether to round partial Case quantities up or down. If the Case-fraction in question is less than the Threshold proportion, it is rounded down; if not, it is rounded up.</retailDoc:documentation>
               </retailDoc:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="round_to_layer_pct" type="number12_4">
               <retailDoc:annotation>
                  <retailDoc:documentation>This column will hold the Layer Rounding Threshold value. During rounding, this value is used to determine whether to round partial Layer quantities up or down. If the Layer-fraction in question is less than the Threshold proportion, it is rounded down; if not, it is rounded up.</retailDoc:documentation>
               </retailDoc:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="round_to_pallet_pct" type="number12_4">
               <retailDoc:annotation>
                  <retailDoc:documentation>This column will hold the Pallet Rounding Threshold value. During rounding, this value is used to determine whether to round partial Pallet quantities up or down. If the Pallet -fraction in question is less than the Threshold proportion, it is rounded down; if not, it is rounded up.</retailDoc:documentation>
               </retailDoc:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="supp_hier_type_1" type="varchar26">
               <retailDoc:annotation>
                  <retailDoc:documentation>This field identifies partner type of supplier hierarchy level 1.This field will always have the partner type S1 which indicates manufacturer..</retailDoc:documentation>
               </retailDoc:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="supp_hier_lvl_1" type="varchar210">
               <retailDoc:annotation>
                  <retailDoc:documentation>Highest level of supplier hierarchy which is there to indicate a partner, such as a manufacturer, in the supply chain that gives rebates to the retailer.</retailDoc:documentation>
               </retailDoc:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="supp_hier_type_2" type="varchar26">
               <retailDoc:annotation>
                  <retailDoc:documentation>This field identifies partner type of supplier hierarchy level 2 . This field will always have the partner type S2 which indicates distributor.</retailDoc:documentation>
               </retailDoc:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="supp_hier_lvl_2" type="varchar210">
               <retailDoc:annotation>
                  <retailDoc:documentation>Second highest level of supplier hierarchy which is there to indicate a partner, such as a distributor in the supply chain that gives rebates to the retailer.</retailDoc:documentation>
               </retailDoc:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="supp_hier_type_3" type="varchar26">
               <retailDoc:annotation>
                  <retailDoc:documentation>This field identifies partner type of supplier hierarchy level 3.This field will always have the partner type S3 which indicates wholesaler.</retailDoc:documentation>
               </retailDoc:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="supp_hier_lvl_3" type="varchar210">
               <retailDoc:annotation>
                  <retailDoc:documentation>Third highest level of supplier hierarchy which is uder to indicate a partner, such as a wholesaler in the supply chain that gives rebates to the retailer.</retailDoc:documentation>
               </retailDoc:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="negotiated_item_cost" type="number20_4">
               <retailDoc:annotation>
                  <retailDoc:documentation>This will hold the supplier negotiated item cost for the primary delivery country of the item. Once a location is associated with the item, the primary locations negotiated item cost will be stored in this field.</retailDoc:documentation>
               </retailDoc:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="extended_base_cost" type="number20_4">
               <retailDoc:annotation>
                  <retailDoc:documentation>This will hold the extended base cost for the primary delivery country of the item. Once a location is associated with the item, the primary locations extended base cost will be stored in this field. Extended base cost is the cost inclusive of all the taxes that affect the WAC. In case of GTAX , Extended Base Cost = Base Cost + Non-recoverable taxes. In case of VAT, Extended Base Cost = Base Cost.</retailDoc:documentation>
               </retailDoc:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="inclusive_cost" type="number20_4">
               <retailDoc:annotation>
                  <retailDoc:documentation>This will hold the inclusive cost for the primary delivery country of the item. Once a location is associated with the item, the primary locations inclusive cost will be stored in this field. This cost will have both the recoverable and non recoverable taxes included. In case of GTAX , Inclusive Cost = Base Cost + Non-recoverable taxes + Recoverable Taxes. In case of VAT, Inclusive Cost = Base Cost + VAT.</retailDoc:documentation>
               </retailDoc:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="base_cost" type="number20_4">
               <retailDoc:annotation>
                  <retailDoc:documentation>This field will hold the tax exclusive cost of the item.</retailDoc:documentation>
               </retailDoc:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="purchase_type" type="varchar21">
               <retailDoc:annotation>
                  <retailDoc:documentation>This contains a code to indicate whether the item is normal merchandise (i.e. owned by the retailer), consignment stock or a concession item. Valid values are 0 - Owned, 1 - Consignment, 2 - Concession.</retailDoc:documentation>
               </retailDoc:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="calculation_basis" type="varchar21">
               <retailDoc:annotation>
                  <retailDoc:documentation>This indicates if the cost for the consignment/concession item will be managed either based on cost per unit or as a percentage of retail. Valid values are C - Cost per Unit, P - Purchase Rate.</retailDoc:documentation>
               </retailDoc:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="purchase_rate" type="number12_4">
               <retailDoc:annotation>
                  <retailDoc:documentation>This column contains the percentage of the retail price which will determnie the cost paid to the supplier for a consignment or concession item.</retailDoc:documentation>
               </retailDoc:annotation>
            </xs:element>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   <xs:simpleType name="varchar210">
      <retailDoc:annotation>
         <retailDoc:documentation>This type can hold a string of max length of 10 characters.</retailDoc:documentation>
      </retailDoc:annotation>
      <xs:restriction base="xs:string">
         <xs:maxLength value="10"/>
      </xs:restriction>
   </xs:simpleType>
   <xs:simpleType name="varchar26">
      <retailDoc:annotation>
         <retailDoc:documentation>This type can hold a string of max length of 6 characters.</retailDoc:documentation>
      </retailDoc:annotation>
      <xs:restriction base="xs:string">
         <xs:maxLength value="6"/>
      </xs:restriction>
   </xs:simpleType>
   <xs:simpleType name="varchar24">
      <retailDoc:annotation>
         <retailDoc:documentation>This type can hold a string of max length of 4 characters.</retailDoc:documentation>
      </retailDoc:annotation>
      <xs:restriction base="xs:string">
         <xs:maxLength value="4"/>
      </xs:restriction>
   </xs:simpleType>
   <xs:simpleType name="varchar23">
      <retailDoc:annotation>
         <retailDoc:documentation>This type can hold a string of max length of 3 characters.</retailDoc:documentation>
      </retailDoc:annotation>
      <xs:restriction base="xs:string">
         <xs:maxLength value="3"/>
      </xs:restriction>
   </xs:simpleType>
   <xs:simpleType name="varchar225">
      <retailDoc:annotation>
         <retailDoc:documentation>This type can hold a string of max length of 25 characters.</retailDoc:documentation>
      </retailDoc:annotation>
      <xs:restriction base="xs:string">
         <xs:maxLength value="25"/>
      </xs:restriction>
   </xs:simpleType>
   <xs:simpleType name="varchar21">
      <retailDoc:annotation>
         <retailDoc:documentation>This type can hold a string of max length of 1 characters.</retailDoc:documentation>
      </retailDoc:annotation>
      <xs:restriction base="xs:string">
         <xs:maxLength value="1"/>
      </xs:restriction>
   </xs:simpleType>
   <xs:simpleType name="number4">
      <retailDoc:annotation>
         <retailDoc:documentation>This type can hold a number of digits count 4.</retailDoc:documentation>
      </retailDoc:annotation>
      <xs:restriction base="xs:int">
         <xs:totalDigits value="4"/>
      </xs:restriction>
   </xs:simpleType>
   <xs:simpleType name="number20_4">
      <retailDoc:annotation>
         <retailDoc:documentation>This type can hold a number of digits count 20 and fraction digit count of 4.</retailDoc:documentation>
      </retailDoc:annotation>
      <xs:restriction base="xs:decimal">
         <xs:totalDigits value="20"/>
         <xs:fractionDigits value="4"/>
      </xs:restriction>
   </xs:simpleType>
   <xs:simpleType name="number12_4">
      <retailDoc:annotation>
         <retailDoc:documentation>This type can hold a number of digits count 12 and fraction digit count of 4.</retailDoc:documentation>
      </retailDoc:annotation>
      <xs:restriction base="xs:decimal">
         <xs:totalDigits value="12"/>
         <xs:fractionDigits value="4"/>
      </xs:restriction>
   </xs:simpleType>
</xs:schema>

=== Hemazinc123/mfcs-int-1024p/src/main/resources/api/Examples/ItemSupCtyMod.xml
<ItemSupCtyDesc
	xmlns="http://www.oracle.com/retail/integration/base/bo/ItemSupCtyDesc/v1"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.oracle.com/retail/integration/base/bo/ItemSupCtyDesc/v1 http://www.oracle.com/retail/integration/base/bo/ItemSupCtyDesc/v1/ItemSupCtyDesc.xsd ">
	<item>sGoUAlCoEpRNoBUIVHrByæ±</item>
	<supplier>NyyZpeæ±</supplier>
	<origin_country_id>a</origin_country_id>
	<primary_supp_ind>a</primary_supp_ind>
	<primary_country_ind>a</primary_country_ind>
	<unit_cost>20.4</unit_cost>
	<lead_time>4</lead_time>
	<pickup_lead_time>4</pickup_lead_time>
	<supp_pack_size>12.4</supp_pack_size>
	<inner_pack_size>12.4</inner_pack_size>
	<round_lvl>Jhæ±</round_lvl>
	<min_order_qty>12.4</min_order_qty>
	<max_order_qty>12.4</max_order_qty>
	<packing_method>zMæ±</packing_method>
	<default_uop>Yyæ±</default_uop>
	<ti>12.4</ti>
	<hi>12.4</hi>
	<cost_uom>æ±</cost_uom>
	<tolerance_type>GHæ±</tolerance_type>
	<max_tolerance>12.4</max_tolerance>
	<min_tolerance>12.4</min_tolerance>
	<ns1:CustFlexAttriVo
		xmlns:ns1="http://www.oracle.com/retail/integration/base/bo/CustFlexAttriVo/v1">
		<ns1:name>vGdrcwVYUVfIxCPEhNSuLvZCRaæ±</ns1:name>
		<ns1:value>BkHKINNkNVsfrTRHzCDnzWpHXknTwiTFoyizemGDNLXxsZRRYQNnhspWGaguuaulWGyBWWZwPHwvCDUyAWzSZuSwRCqWLYwyiSTgqYQlaquYyeTdDMQRWIHfOZdPiCTLgpdGWjYJqLTRMgHToXchRhiABhpcwPnLOTQSsaMuUHqMneHYUUogvUQoMAAvfcyKMvaoHwGCahJcXHIpdXsbnBrSasuZxbMRNzQTNCamGJTyNkATmGrqWnæ±</ns1:value>
		<ns1:value_date>2013-09-01T09:08:07</ns1:value_date>
	</ns1:CustFlexAttriVo>
	<round_to_inner_pct>12.4</round_to_inner_pct>
	<round_to_case_pct>12.4</round_to_case_pct>
	<round_to_layer_pct>12.4</round_to_layer_pct>
	<round_to_pallet_pct>12.4</round_to_pallet_pct>
	<supp_hier_type_1>peæ±</supp_hier_type_1>
	<supp_hier_lvl_1>uXxAuIæ±</supp_hier_lvl_1>
	<supp_hier_type_2>SBæ±</supp_hier_type_2>
	<supp_hier_lvl_2>dfYZdNæ±</supp_hier_lvl_2>
	<supp_hier_type_3>mkæ±</supp_hier_type_3>
	<supp_hier_lvl_3>UkcbXFæ±</supp_hier_lvl_3>
	<negotiated_item_cost>20.4</negotiated_item_cost>
	<extended_base_cost>20.4</extended_base_cost>
	<inclusive_cost>20.4</inclusive_cost>
	<base_cost>20.4</base_cost>
	<purchase_type>a</purchase_type>
	<calculation_basis>a</calculation_basis>
	<purchase_rate>12.4</purchase_rate>
</ItemSupCtyDesc>
